// Package externemit generates the shim.mochi Mochi source file containing
// extern fn declarations and extern type stubs for a translated Erlang package.
//
// For each package, one shim.mochi file is emitted. It contains:
//
//  1. extern type stubs for pid, port, reference (the Erlang externs).
//  2. One extern fn declaration per translated function spec.
//  3. A SKIPPED.txt comment block listing all SkipReports for the package.
//
// The generated file is placed at:
//
//	<workdir>/erlang_shims/<appname>/<appname>.mochi
//
// Extern fn syntax (from MEP-66 §5.3):
//
//	extern fn cowboy_mochi_shim::start_clear(name: string, port: int) result<unit, string>
//
// The extern fn name maps to the gen_server call in shim.erl via the
// "module:function" dispatch key.
package externemit

import (
	"fmt"
	"strings"

	breakers "github.com/mochilang/mochi-beam/errors"
	"github.com/mochilang/mochi-beam/typemap"
)

// FnDecl is the data needed to emit one extern fn declaration.
type FnDecl struct {
	// ShimModule is the Erlang shim module name (e.g. "cowboy_mochi_shim").
	ShimModule string
	// Function is the Mochi extern fn name (Erlang function name).
	Function string
	// Args is the list of (name, type) pairs for the function parameters.
	Args []ArgDecl
	// Return is the return Mochi type string.
	Return string
}

// ArgDecl is a single argument declaration.
type ArgDecl struct {
	Name string
	Type typemap.MochiType
}

// SkipEntry records one function that was skipped during translation.
type SkipEntry struct {
	Module   string
	Function string
	Arity    int
	Position string
	Report   breakers.SkipReport
}

// EmitShimMochi generates the shim.mochi source for a package.
// pkgName is the Hex.pm / OTP package name. fns is the list of translated
// functions. skipped is the list of skip reports.
func EmitShimMochi(pkgName string, fns []FnDecl, skipped []breakers.SkipReport) string {
	var sb strings.Builder
	shimModule := pkgName + "_mochi_shim"

	sb.WriteString(fmt.Sprintf("// Mochi extern bindings for Erlang package %q\n", pkgName))
	sb.WriteString("// Auto-generated by the MEP-66 bridge; do not edit manually.\n\n")

	// Extern type stubs (Erlang-specific OTP handle types).
	sb.WriteString("// OTP handle types (opaque wrappers around Erlang runtime values)\n")
	sb.WriteString("extern type erlang.Pid\n")
	sb.WriteString("extern type erlang.Port\n")
	sb.WriteString("extern type erlang.Reference\n\n")

	// Extern fn declarations.
	if len(fns) > 0 {
		sb.WriteString("// Extern fn declarations\n")
		for _, fn := range fns {
			sb.WriteString(fmt.Sprintf("extern fn %s::%s(", shimModule, fn.Function))
			for i, arg := range fn.Args {
				if i > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(fmt.Sprintf("%s: %s", arg.Name, arg.Type))
			}
			sb.WriteString(fmt.Sprintf(") %s\n", fn.Return))
		}
		sb.WriteString("\n")
	}

	// SKIPPED block.
	if len(skipped) > 0 {
		sb.WriteString("// SKIPPED functions (not translated; see package3/erlang/errors for reason codes)\n")
		sb.WriteString("//\n")
		for _, s := range skipped {
			for _, line := range strings.Split(s.String(), "\n") {
				if line != "" {
					sb.WriteString("// " + line + "\n")
				}
			}
		}
	}

	return sb.String()
}

// EmitSkippedTxt generates the SKIPPED.txt file content for a package.
// This is the human-readable skip report placed in erlang_shims/<app>/SKIPPED.txt.
func EmitSkippedTxt(skipped []breakers.SkipReport) string {
	if len(skipped) == 0 {
		return "No skipped functions.\n"
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("Total skipped: %d\n\n", len(skipped)))
	for _, s := range skipped {
		sb.WriteString(s.String())
	}
	return sb.String()
}
