package lockfile

import (
	"fmt"
	"strings"
)

// RenderTOML produces a deterministic TOML fragment for m. The output
// is suitable for appending to an existing mochi.lock file. Entries are
// sorted by Name before rendering.
//
// Header comment:
//
//	# Auto-generated by mochi pkg lock (MEP-66). Do not edit by hand.
//	# Regenerate via `mochi pkg lock`.
//	erlang-lockfile-schema = 1
func RenderTOML(m Manifest) string {
	out := m
	out.Sort()
	v := out.Version
	if v == 0 {
		v = SchemaVersion
	}
	var b strings.Builder
	b.WriteString("# Auto-generated by mochi pkg lock (MEP-66). Do not edit by hand.\n")
	b.WriteString("# Regenerate via `mochi pkg lock`.\n")
	fmt.Fprintf(&b, "erlang-lockfile-schema = %d\n\n", v)
	for _, e := range out.Entries {
		renderEntry(&b, e)
	}
	return b.String()
}

func renderEntry(b *strings.Builder, e Entry) {
	b.WriteString("[[erlang-package]]\n")
	fmt.Fprintf(b, "name = %q\n", e.Name)
	fmt.Fprintf(b, "version = %q\n", e.Version)
	registry := e.Registry
	if registry == "" {
		registry = "https://hex.pm"
	}
	fmt.Fprintf(b, "registry = %q\n", registry)
	if e.OuterSHA256 != "" {
		fmt.Fprintf(b, "outer-sha256 = %q\n", e.OuterSHA256)
	}
	if e.InnerSHA256 != "" {
		fmt.Fprintf(b, "inner-sha256 = %q\n", e.InnerSHA256)
	}
	if e.InnerSHA512 != "" {
		fmt.Fprintf(b, "inner-sha512 = %q\n", e.InnerSHA512)
	}
	if e.BeamIngestSHA256 != "" {
		fmt.Fprintf(b, "beam-ingest-sha256 = %q\n", e.BeamIngestSHA256)
	}
	if e.ShimSHA256 != "" {
		fmt.Fprintf(b, "shim-sha256 = %q\n", e.ShimSHA256)
	}
	if e.OTPApp != "" && e.OTPApp != e.Name {
		fmt.Fprintf(b, "otp-app = %q\n", e.OTPApp)
	}
	if len(e.Capabilities) > 0 {
		b.WriteString("capabilities = [")
		for i, c := range e.Capabilities {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%q", c)
		}
		b.WriteString("]\n")
	}
	if len(e.Dependencies) > 0 {
		b.WriteString("dependencies = [")
		for i, d := range e.Dependencies {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%q", d)
		}
		b.WriteString("]\n")
	}
	if len(e.Modules) > 0 {
		b.WriteString("modules = [")
		for i, mod := range e.Modules {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%q", mod)
		}
		b.WriteString("]\n")
	}
	b.WriteString("\n")
}
